[profile.default]
solc-version = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]
"@openzeppelin/contracts" = "specific_version_compatible_with_0.8.19"
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options